language: python
cache: pip
sudo: false

env:
  global:
    - PILLOW_VERSION=3.2.0

matrix:
  include:
    - python: 2.7
      env: PILLOW_VERSION=2.9.0
    - python: 2.7
      env: PILLOW_VERSION=3.0.0
    - python: 2.7
    - python: 3.3
    - python: 3.4
    - python: 3.5


addons:
  apt:
    packages:
      - ubuntu-restricted-extras
      - ffmpeg
      - language-pack-fr
      - libavcodec-extra-54
    sources:
      # Dependencies to build PIL
      - libfreetype6-dev
      - libjpeg8-dev
      - zlib1g-dev

install:
    - pip install -q Pillow==$PILLOW_VERSION
    - pip install pytest pytest-cov coveralls
    - pip install .

before_script:
  ffmpeg --help

script: py.test -sv --cov sigal --cov-report term-missing tests/

after_success:
    coveralls

notifications:
    irc: "chat.freenode.net#sigal"
