language: python
python:
    - "2.7"
    - "2.6"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-pyexiv2
    # Dependencies to build PIL
    - sudo apt-get install -qq libfreetype6-dev libjpeg8-dev zlib1g-dev
install:
    - pip install nose unittest2 --use-mirrors
    - pip install . --use-mirrors
script: nosetests
